---
title: "extract_zotero_bib.Rmd"
author: "Julien Tap"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load_lib}

library(RCurl)
library(XML)
library(bibtex)
library(RefManageR)

```

```{r get_id}

groupId = "4861855"

apiKey = Sys.getenv("ZOTERO_API_KEY")


```



```{r zotero_api}
url <- paste("https://api.zotero.org/groups/", groupId, "/items?format=bib&v=3&key=", apiKey, sep="")
bibtex <- getURL(url)
```

```{r render_bib}

if(file.exists("FME_publications_2.bib")) {

  file.remove("FME_publications_2.bib") }


  RefManageR::ReadZotero(group = groupId, .params = list(
  key = apiKey), temp.file = "FME_publications_2.bib", delete.file = FALSE) -> res.bib



```

```{r sort_bib, message=FALSE, warning=FALSE}
library(RefManageR)

bib_file <- read.bib("FME_publications_2.bib")

years <- vapply(seq_along(bib_file), function(i) {
  x <- bib_file[[i]][[1]]
  
  y <- x$year
  
  if (is.null(y) || length(y) == 0) {
    return(NA_real_)
  }
  
  y <- as.character(y)[1]  # force scalar
  
  suppressWarnings(as.numeric(substr(y, 1, 4)))
}, numeric(1))

bib_file <- bib_file[order(years, decreasing = TRUE, na.last = TRUE)]

write.bib(bib_file, file = "FME_publications_sorted_2.bib")

```



```{r render_publications}

rmarkdown::render("index.Rmd")


```




